### ISSUE TITLE
hi,thanks for your code,I wonder if there is a script to test this algorithm

### ISSUE THREAD

**Issue by OOOred** [winlaic/deepIQA_torch#1]
I wonder if there is a script to test this algorithm？i m new in IQA,hoping to have your reply,tttttanksssss!!!!!

**Comment by winlaic** [comment]
I'm so sorry! Please **DO NOT** use the model for evaluation of the algorithm! The code is a **draft** which I wrote carelessly when I began to learn IQA. The training methodology is not right, some images for testing is mixed into training set. I have removed the wrong model from the source. If you want to use the code right now, please rewrite the code in `dataset.py` for generation of the metadata. I will soon rewrite the code and repost the complete version.
